# -*- coding: utf-8 -*-
"""Digit Classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aHyWJi9XF5AlyfrW7rk-TxByECUkrNal
"""

#Cau 3
class DigitClassificationModel(object):
    """
    A model for handwritten digit classification using the MNIST dataset.

    Each handwritten digit is a 28x28 pixel grayscale image, which is flattened
    into a 784-dimensional vector for the purposes of this model. Each entry in
    the vector is a floating point number between 0 and 1.

    The goal is to sort each digit into one of 10 classes (number 0 through 9).

    (See RegressionModel for more information about the APIs of different
    methods here. We recommend that you implement the RegressionModel before
    working on this part of the project.)
    """
    def __init__(self):
        # Initialize your model parameters here
        "*** YOUR CODE HERE ***"
        input_size = 784
        hidden_layer_size = 200  # suggested size
        output_size = 10 # 10 classes (digits 0->9)

        self.W1 = nn.Parameter(input_size, hidden_layer_size)
        self.b1 = nn.Parameter(1, hidden_layer_size)
        self.W2 = nn.Parameter(hidden_layer_size, output_size)
        self.b2 = nn.Parameter(1, output_size)

    def run(self, x):
        """
        Runs the model for a batch of examples.

        Your model should predict a node with shape (batch_size x 10),
        containing scores. Higher scores correspond to greater probability of
        the image belonging to a particular class.

        Inputs:
            x: a node with shape (batch_size x 784)
        Output:
            A node with shape (batch_size x 10) containing predicted scores
                (also called logits)
        """
        "*** YOUR CODE HERE ***"
        x = nn.Linear(x, self.W1)
        x = nn.AddBias(x, self.b1)
        x = nn.ReLU(x)
        x = nn.Linear(x, self.W2)
        x = nn.AddBias(x, self.b2)
        return x

    def get_loss(self, x, y):
        """
        Computes the loss for a batch of examples.

        The correct labels `y` are represented as a node with shape
        (batch_size x 10). Each row is a one-hot vector encoding the correct
        digit class (0-9).

        Inputs:
            x: a node with shape (batch_size x 784)
            y: a node with shape (batch_size x 10)
        Returns: a loss node
        """
        "*** YOUR CODE HERE ***"
        predicted_value = self.run(x)
        return nn.SoftmaxLoss(predicted_value, y)

    def train(self, dataset):
        """
        Trains the model.
        """
        "*** YOUR CODE HERE ***"
        learning_rate = 0.5 # as suggested
        batch_size = 100 # suggest

        while True:
            for x, y in dataset.iterate_once(batch_size):
                loss = self.get_loss(x, y)
                gradients = nn.gradients(loss, [self.W1, self.b1, self.W2, self.b2])
                self.W1.update(gradients[0], -learning_rate)
                self.b1.update(gradients[1], -learning_rate)
                self.W2.update(gradients[2], -learning_rate)
                self.b2.update(gradients[3], -learning_rate)
            print(f"Accuracy: {dataset.get_validation_accuracy()}")
            if dataset.get_validation_accuracy() > 0.98:
                return