# -*- coding: utf-8 -*-
"""Language Identification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1smFV1QGRGfJZbbxfaR9ccM0JSgwonfdZ
"""

class LanguageIDModel(object):
    """
    A model for language identification at a single-word granularity.

    (See RegressionModel for more information about the APIs of different
    methods here. We recommend that you implement the RegressionModel before
    working on this part of the project.)
    """
    def __init__(self):
        # Our dataset contains words from five different languages, and the
        # combined alphabets of the five languages contain a total of 47 unique
        # characters.
        # You can refer to self.num_chars or len(self.languages) in your code
        self.num_chars = 47
        self.languages = ["English", "Spanish", "Finnish", "Dutch", "Polish"]

        # Initialize your model parameters here
        "*** YOUR CODE HERE ***"
        hidden_size = 200
        self.W_initial = nn.Parameter(self.num_chars, hidden_size)
        self.W_hidden = nn.Parameter(hidden_size, hidden_size)
        self.Wx = nn.Parameter(self.num_chars, hidden_size)
        self.W_final = nn.Parameter(hidden_size, len(self.languages))
        self.b_final = nn.Parameter(1, len(self.languages))

    def run(self, xs):
        """
        Runs the model for a batch of examples.

        Although words have different lengths, our data processing guarantees
        that within a single batch, all words will be of the same length (L).

        Here `xs` will be a list of length L. Each element of `xs` will be a
        node with shape (batch_size x self.num_chars), where every row in the
        array is a one-hot vector encoding of a character. For example, if we
        have a batch of 8 three-letter words where the last word is "cat", then
        xs[1] will be a node that contains a 1 at position (7, 0). Here the
        index 7 reflects the fact that "cat" is the last word in the batch, and
        the index 0 reflects the fact that the letter "a" is the inital (0th)
        letter of our combined alphabet for this task.

        Your model should use a Recurrent Neural Network to summarize the list
        `xs` into a single node of shape (batch_size x hidden_size), for your
        choice of hidden_size. It should then calculate a node of shape
        (batch_size x 5) containing scores, where higher scores correspond to
        greater probability of the word originating from a particular language.

        Inputs:
            xs: a list with L elements (one per character), where each element
                is a node with shape (batch_size x self.num_chars)
        Returns:
            A node with shape (batch_size x 5) containing predicted scores
                (also called logits)
        """
        "*** YOUR CODE HERE ***"
        trans = nn.Linear(xs[0], self.W_initial)

        # each character in word
        for c in xs[1:]:
            a = nn.Add(nn.Linear(c, self.Wx), nn.Linear(trans, self.W_hidden))
            trans = nn.ReLU(a)
        result = nn.AddBias(nn.Linear(trans, self.W_final), self.b_final)
        return result
    def get_loss(self, xs, y):
        """
        Computes the loss for a batch of examples.

        The correct labels `y` are represented as a node with shape
        (batch_size x 5). Each row is a one-hot vector encoding the correct
        language.

        Inputs:
            xs: a list with L elements (one per character), where each element
                is a node with shape (batch_size x self.num_chars)
            y: a node with shape (batch_size x 5)
        Returns: a loss node
        """
        "*** YOUR CODE HERE ***"
        predicted_value = self.run(xs)
        return nn.SoftmaxLoss(predicted_value, y)

    def train(self, dataset):
        """
        Trains the model.
        """
        "*** YOUR CODE HERE ***"
        threshold = 0.87
        learning_rate = 0.1
        batch_size = 100

        while True:
            for xs, y in dataset.iterate_once(batch_size):
                loss = self.get_loss(xs, y)
                gradients = nn.gradients(loss, [self.W_initial, self.W_hidden, self.Wx, self.W_final, self.b_final])

                #update value of parameters
                self.W_initial.update(gradients[0], -learning_rate)
                self.W_hidden.update(gradients[1], -learning_rate)
                self.Wx.update(gradients[2], -learning_rate)
                self.W_final.update(gradients[3], -learning_rate)
                self.b_final.update(gradients[4], -learning_rate)
            print(f"Accuracy: {dataset.get_validation_accuracy()}")
            if dataset.get_validation_accuracy() > threshold:
                return